name: 'cinema_atlas'
version: '1.0.0'
config-version: 2

profile: 'cinema_atlas'

model-paths: ["models"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  tmdb_catalog: workspace
  bronze_schema: bronze
  silver_schema: silver

models:
  cinema_atlas:
    staging:
      +materialized: view
      +schema: staging_cinema_atlas
    silver:
      +materialized: table
      +schema: silver_cinema_atlas
      tmdb:
        +tags: ["tmdb"]